import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./Component/Home/Nav";
import ClientProvider from "./Component/Hoc/ClientProvider";
import { AppWrapper } from "./Component/Context/Provider";
import Footer from "./Component/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "jobportal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProvider>
      <AppWrapper>
        <html lang="en">
          <body className={inter.className}>
            <Nav />
            {children}
            <Footer />
          </body>
        </html>
      </AppWrapper>
    </ClientProvider>
  );
}
